syntax = "proto3";

package com.github.guihigashi.conduit.feed;

option go_package = "github.com/guihigashi/conduit/feed/internal/generated/pbfeed;pbfeed";

option php_namespace = "Generated\\Grpc\\Feed";
option php_metadata_namespace = "Generated\\Grpc\\Feed\\Metadata";

service FeedService {
  rpc GetFeed (GetFeedRequest) returns (GetFeedResponse);
}

message GetFeedRequest {
  int32 limit = 1;
  int32 offset = 2;
}

message Article {
  string slug = 1;
  string title = 2;
  string description = 3;
  repeated string tag_list = 4;
  string created_at = 5;
  string updated_at = 6;
  bool favorited = 7;
  int32 favorites_count = 8;
  Author author = 9;
}

message Author {
  string username = 1;
  string bio = 2;
  string image = 3;
  bool following = 4;
}

message GetFeedResponse {
  repeated Article articles = 1;
  int32 articles_count = 2;
}