syntax = "proto3";

package com.github.guihigashi.conduit.article;

import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_package = "com.github.guihigashi.conduit.article.grpc";

option php_namespace = "Generated\\Grpc\\Article";
option php_metadata_namespace = "Generated\\Grpc\\Article\\Metadata";

service ArticleService {
  rpc GetArticle (GetArticleRequest) returns (ArticleResponse);
  rpc ListArticles (ListArticlesRequest) returns (ListArticlesResponse);
  rpc CreateArticle (CreateArticleRequest) returns (ArticleResponse);
  rpc GetTags (google.protobuf.Empty) returns (TagListResponse);
  rpc FavoriteArticle (FavoriteArticleRequest) returns (ArticleResponse);
  rpc UnfavoriteArticle (UnfavoriteArticleRequest) returns (ArticleResponse);
}

message GetArticleRequest {
  string slug = 1;
  string requestor_id = 2; // For calculating 'favorited' status
}

message ListArticlesRequest {
  optional string tag = 1;
  optional string author_id = 2;
  optional string favorited_by_id = 3;
  int32 limit = 4;
  int32 offset = 5;
  optional string requestor_id = 6;
}

message CreateArticleRequest {
  string title = 1;
  string description = 2;
  string body = 3;
  repeated string tag_list = 4;
  string author_id = 5;
}

message Article {
  string slug = 1;
  string title = 2;
  string description = 3;
  string body = 4;
  repeated string tag_list = 5;
  string created_at = 6;
  string updated_at = 7;
  bool favorited = 8;
  int32 favorites_count = 9;
  string author_id = 10;
}

message ArticleResponse {
  Article article = 1;
}

message ListArticlesResponse {
  repeated Article articles = 1;
}

message TagListResponse {
  repeated string tags = 1;
}

message FavoriteArticleRequest {
  string slug = 1;
  string requestor_id = 2;
}

message UnfavoriteArticleRequest {
  string slug = 1;
  string requestor_id = 2;
}