// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: social_graph.proto

package pbsocial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerId     string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"` // From the PHP Gateway JWT
	TargetUsername string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_social_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type UnfollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerId     string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	TargetUsername string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_social_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{1}
}

func (x *UnfollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnfollowRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type GetProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestorId    *string                `protobuf:"bytes,1,opt,name=requestor_id,json=requestorId,proto3,oneof" json:"requestor_id,omitempty"`
	TargetUsername string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_social_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetRequestorId() string {
	if x != nil && x.RequestorId != nil {
		return *x.RequestorId
	}
	return ""
}

func (x *GetProfileRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type GetProfilesByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	RequestorId   string                 `protobuf:"bytes,2,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesByIdsRequest) Reset() {
	*x = GetProfilesByIdsRequest{}
	mi := &file_social_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesByIdsRequest) ProtoMessage() {}

func (x *GetProfilesByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesByIdsRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfilesByIdsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetProfilesByIdsRequest) GetRequestorId() string {
	if x != nil {
		return x.RequestorId
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           *string                `protobuf:"bytes,2,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Image         *string                `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_social_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileResponse) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *ProfileResponse) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ProfileResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type ProfilesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Profiles      map[string]*ProfileResponse `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesResponse) Reset() {
	*x = ProfilesResponse{}
	mi := &file_social_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesResponse) ProtoMessage() {}

func (x *ProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesResponse.ProtoReflect.Descriptor instead.
func (*ProfilesResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{5}
}

func (x *ProfilesResponse) GetProfiles() map[string]*ProfileResponse {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpsertProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileRequest) Reset() {
	*x = UpsertProfileRequest{}
	mi := &file_social_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileRequest) ProtoMessage() {}

func (x *UpsertProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertProfileRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpsertProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpsertProfileRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type UpsertProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProfileResponse) Reset() {
	*x = UpsertProfileResponse{}
	mi := &file_social_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProfileResponse) ProtoMessage() {}

func (x *UpsertProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertProfileResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResolveIdsByUsernamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdsByUsernamesRequest) Reset() {
	*x = ResolveIdsByUsernamesRequest{}
	mi := &file_social_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdsByUsernamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsByUsernamesRequest) ProtoMessage() {}

func (x *ResolveIdsByUsernamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsByUsernamesRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdsByUsernamesRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveIdsByUsernamesRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type ResolveIdsByUsernamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResolvedIds   map[string]string      `protobuf:"bytes,1,rep,name=resolved_ids,json=resolvedIds,proto3" json:"resolved_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdsByUsernamesResponse) Reset() {
	*x = ResolveIdsByUsernamesResponse{}
	mi := &file_social_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdsByUsernamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsByUsernamesResponse) ProtoMessage() {}

func (x *ResolveIdsByUsernamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsByUsernamesResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdsByUsernamesResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveIdsByUsernamesResponse) GetResolvedIds() map[string]string {
	if x != nil {
		return x.ResolvedIds
	}
	return nil
}

var File_social_graph_proto protoreflect.FileDescriptor

const file_social_graph_proto_rawDesc = "" +
	"\n" +
	"\x12social_graph.proto\x12$com.github.guihigashi.conduit.social\"Y\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\"[\n" +
	"\x0fUnfollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\"u\n" +
	"\x11GetProfileRequest\x12&\n" +
	"\frequestor_id\x18\x01 \x01(\tH\x00R\vrequestorId\x88\x01\x01\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsernameB\x0f\n" +
	"\r_requestor_id\"W\n" +
	"\x17GetProfilesByIdsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12!\n" +
	"\frequestor_id\x18\x02 \x01(\tR\vrequestorId\"\x8f\x01\n" +
	"\x0fProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x15\n" +
	"\x03bio\x18\x02 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x03 \x01(\tH\x01R\x05image\x88\x01\x01\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowingB\x06\n" +
	"\x04_bioB\b\n" +
	"\x06_image\"\xe8\x01\n" +
	"\x10ProfilesResponse\x12`\n" +
	"\bprofiles\x18\x01 \x03(\v2D.com.github.guihigashi.conduit.social.ProfilesResponse.ProfilesEntryR\bprofiles\x1ar\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12K\n" +
	"\x05value\x18\x02 \x01(\v25.com.github.guihigashi.conduit.social.ProfileResponseR\x05value:\x028\x01\"s\n" +
	"\x14UpsertProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"1\n" +
	"\x15UpsertProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x1cResolveIdsByUsernamesRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\"\xd8\x01\n" +
	"\x1dResolveIdsByUsernamesResponse\x12w\n" +
	"\fresolved_ids\x18\x01 \x03(\v2T.com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse.ResolvedIdsEntryR\vresolvedIds\x1a>\n" +
	"\x10ResolvedIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xce\x06\n" +
	"\x12SocialGraphService\x12x\n" +
	"\n" +
	"FollowUser\x123.com.github.guihigashi.conduit.social.FollowRequest\x1a5.com.github.guihigashi.conduit.social.ProfileResponse\x12|\n" +
	"\fUnfollowUser\x125.com.github.guihigashi.conduit.social.UnfollowRequest\x1a5.com.github.guihigashi.conduit.social.ProfileResponse\x12|\n" +
	"\n" +
	"GetProfile\x127.com.github.guihigashi.conduit.social.GetProfileRequest\x1a5.com.github.guihigashi.conduit.social.ProfileResponse\x12\x89\x01\n" +
	"\x10GetProfilesByIds\x12=.com.github.guihigashi.conduit.social.GetProfilesByIdsRequest\x1a6.com.github.guihigashi.conduit.social.ProfilesResponse\x12\x92\x01\n" +
	"\x17UpsertProfileProjection\x12:.com.github.guihigashi.conduit.social.UpsertProfileRequest\x1a;.com.github.guihigashi.conduit.social.UpsertProfileResponse\x12\xa0\x01\n" +
	"\x15ResolveIdsByUsernames\x12B.com.github.guihigashi.conduit.social.ResolveIdsByUsernamesRequest\x1aC.com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponseB\xaf\x01\n" +
	")com.github.guihigashi.conduit.social.grpcP\x01Z=github.com/guihigashi/conduit/feed/internal/pbsocial;pbsocial\xca\x02\x1aGenerated\\Grpc\\SocialGraph\xe2\x02#Generated\\Grpc\\SocialGraph\\Metadatab\x06proto3"

var (
	file_social_graph_proto_rawDescOnce sync.Once
	file_social_graph_proto_rawDescData []byte
)

func file_social_graph_proto_rawDescGZIP() []byte {
	file_social_graph_proto_rawDescOnce.Do(func() {
		file_social_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_graph_proto_rawDesc), len(file_social_graph_proto_rawDesc)))
	})
	return file_social_graph_proto_rawDescData
}

var file_social_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_social_graph_proto_goTypes = []any{
	(*FollowRequest)(nil),                 // 0: com.github.guihigashi.conduit.social.FollowRequest
	(*UnfollowRequest)(nil),               // 1: com.github.guihigashi.conduit.social.UnfollowRequest
	(*GetProfileRequest)(nil),             // 2: com.github.guihigashi.conduit.social.GetProfileRequest
	(*GetProfilesByIdsRequest)(nil),       // 3: com.github.guihigashi.conduit.social.GetProfilesByIdsRequest
	(*ProfileResponse)(nil),               // 4: com.github.guihigashi.conduit.social.ProfileResponse
	(*ProfilesResponse)(nil),              // 5: com.github.guihigashi.conduit.social.ProfilesResponse
	(*UpsertProfileRequest)(nil),          // 6: com.github.guihigashi.conduit.social.UpsertProfileRequest
	(*UpsertProfileResponse)(nil),         // 7: com.github.guihigashi.conduit.social.UpsertProfileResponse
	(*ResolveIdsByUsernamesRequest)(nil),  // 8: com.github.guihigashi.conduit.social.ResolveIdsByUsernamesRequest
	(*ResolveIdsByUsernamesResponse)(nil), // 9: com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse
	nil,                                   // 10: com.github.guihigashi.conduit.social.ProfilesResponse.ProfilesEntry
	nil,                                   // 11: com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse.ResolvedIdsEntry
}
var file_social_graph_proto_depIdxs = []int32{
	10, // 0: com.github.guihigashi.conduit.social.ProfilesResponse.profiles:type_name -> com.github.guihigashi.conduit.social.ProfilesResponse.ProfilesEntry
	11, // 1: com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse.resolved_ids:type_name -> com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse.ResolvedIdsEntry
	4,  // 2: com.github.guihigashi.conduit.social.ProfilesResponse.ProfilesEntry.value:type_name -> com.github.guihigashi.conduit.social.ProfileResponse
	0,  // 3: com.github.guihigashi.conduit.social.SocialGraphService.FollowUser:input_type -> com.github.guihigashi.conduit.social.FollowRequest
	1,  // 4: com.github.guihigashi.conduit.social.SocialGraphService.UnfollowUser:input_type -> com.github.guihigashi.conduit.social.UnfollowRequest
	2,  // 5: com.github.guihigashi.conduit.social.SocialGraphService.GetProfile:input_type -> com.github.guihigashi.conduit.social.GetProfileRequest
	3,  // 6: com.github.guihigashi.conduit.social.SocialGraphService.GetProfilesByIds:input_type -> com.github.guihigashi.conduit.social.GetProfilesByIdsRequest
	6,  // 7: com.github.guihigashi.conduit.social.SocialGraphService.UpsertProfileProjection:input_type -> com.github.guihigashi.conduit.social.UpsertProfileRequest
	8,  // 8: com.github.guihigashi.conduit.social.SocialGraphService.ResolveIdsByUsernames:input_type -> com.github.guihigashi.conduit.social.ResolveIdsByUsernamesRequest
	4,  // 9: com.github.guihigashi.conduit.social.SocialGraphService.FollowUser:output_type -> com.github.guihigashi.conduit.social.ProfileResponse
	4,  // 10: com.github.guihigashi.conduit.social.SocialGraphService.UnfollowUser:output_type -> com.github.guihigashi.conduit.social.ProfileResponse
	4,  // 11: com.github.guihigashi.conduit.social.SocialGraphService.GetProfile:output_type -> com.github.guihigashi.conduit.social.ProfileResponse
	5,  // 12: com.github.guihigashi.conduit.social.SocialGraphService.GetProfilesByIds:output_type -> com.github.guihigashi.conduit.social.ProfilesResponse
	7,  // 13: com.github.guihigashi.conduit.social.SocialGraphService.UpsertProfileProjection:output_type -> com.github.guihigashi.conduit.social.UpsertProfileResponse
	9,  // 14: com.github.guihigashi.conduit.social.SocialGraphService.ResolveIdsByUsernames:output_type -> com.github.guihigashi.conduit.social.ResolveIdsByUsernamesResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_social_graph_proto_init() }
func file_social_graph_proto_init() {
	if File_social_graph_proto != nil {
		return
	}
	file_social_graph_proto_msgTypes[2].OneofWrappers = []any{}
	file_social_graph_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_graph_proto_rawDesc), len(file_social_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_graph_proto_goTypes,
		DependencyIndexes: file_social_graph_proto_depIdxs,
		MessageInfos:      file_social_graph_proto_msgTypes,
	}.Build()
	File_social_graph_proto = out.File
	file_social_graph_proto_goTypes = nil
	file_social_graph_proto_depIdxs = nil
}
