syntax = "proto3";

package com.github.guihigashi.conduit.social;

import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_package = "com.github.guihigashi.conduit.social.grpc";

option go_package = "github.com/guihigashi/conduit/feed/internal/generated/pbsocial;pbsocial";

option php_namespace = "Generated\\Grpc\\SocialGraph";
option php_metadata_namespace = "Generated\\Grpc\\SocialGraph\\Metadata";

service SocialGraphService {
  rpc GetProfile (GetProfileRequest) returns (ProfileResponse);
  rpc FollowUser (FollowRequest) returns (ProfileResponse);
  rpc UnfollowUser (UnfollowRequest) returns (ProfileResponse);

  rpc GetProfilesByIds (GetProfilesByIdsRequest) returns (ProfilesResponse);
  rpc UpsertProfileProjection (UpsertProfileRequest) returns (UpsertProfileResponse);
  rpc ResolveIdsByUsernames (ResolveIdsByUsernamesRequest) returns (ResolveIdsByUsernamesResponse);
  rpc GetFollowing (google.protobuf.Empty) returns (GetFollowingResponse);
}

message GetProfileRequest {
  string target_username = 1;
}

message ProfileResponse {
  string username = 1;
  optional string bio = 2;
  optional string image = 3;
  bool following = 4;
}

message FollowRequest {
  string target_username = 1;
}

message UnfollowRequest {
  string target_username = 1;
}

message GetProfilesByIdsRequest {
  repeated string user_ids = 1;
}

message ProfilesResponse {
  map<string, ProfileResponse> profiles = 1;
}

message UpsertProfileRequest {
  string username = 2;
  string bio = 3;
  string image = 4;
}

message UpsertProfileResponse {
  bool success = 1;
}

message ResolveIdsByUsernamesRequest {
  repeated string usernames = 1;
}

message ResolveIdsByUsernamesResponse {
  map<string, string> resolved_ids = 1;
}

message GetFollowingResponse {
  repeated string following_ids = 1;
}
