syntax = "proto3";

package com.github.guihigashi.conduit.social;

option java_multiple_files = true;
option java_package = "com.github.guihigashi.conduit.social.grpc";

option go_package = "github.com/guihigashi/conduit/social/grpc;social_graph";

option php_namespace = "Generated\\Grpc\\SocialGraph";
option php_metadata_namespace = "Generated\\Grpc\\SocialGraph\\Metadata";

service SocialGraphService {
  // Follow a user
  rpc FollowUser (FollowRequest) returns (ProfileResponse);

  // Unfollow a user
  rpc UnfollowUser (UnfollowRequest) returns (ProfileResponse);

  // Get a user's profile (including if the current user follows them)
  rpc GetProfile (GetProfileRequest) returns (ProfileResponse);

  rpc UpsertProfileProjection (UpsertProfileRequest) returns (UpsertProfileResponse);
}

message FollowRequest {
  string follower_id = 1; // From the PHP Gateway JWT
  string target_username = 2;
}

message UnfollowRequest {
  string follower_id = 1;
  string target_username = 2;
}

message GetProfileRequest {
  optional string requestor_id = 1;
  string target_username = 2;
}

message ProfileResponse {
  string username = 1;
  optional string bio = 2;
  optional string image = 3;
  bool following = 4;
}

message UpsertProfileRequest {
  string user_id = 1;
  string username = 2;
  string bio = 3;
  string image = 4;
}

message UpsertProfileResponse {
  bool success = 1;
}