[environments.default]
url = "jdbc:postgresql://localhost:5432/articles"
user = "realworld"
password = "secret"

[flyway]
environment = "default"
locations = ["filesystem:src/main/resources/db/migration"]
cleanDisabled = false