FROM docker.io/library/php:8.5-zts

RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/mlocati/php-extension-installer:latest /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    bcmath \
    grpc \
    intl \
    opcache \
    pcntl \
    pdo_pgsql \
    redis \
    swoole \
    zip

COPY --from=docker.io/library/composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

VOLUME /app/storage/logs

RUN composer dump-autoload --optimize && php artisan optimize:clear

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]
